theme = "custom"

[editor]
scrolloff = 10
line-number = "relative"
# cursorline = true
color-modes = true
mouse = true
idle-timeout = 0
bufferline = "always"
auto-save = true
lsp.display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[keys.normal]
X = "extend_line_above"
esc = ["collapse_selection", "keep_primary_selection"]
space = { w = ":update", q = ":bc", e = ":sh explorer.exe . | exit 0" }
