theme = "custom"

[editor]
scrolloff = 20
line-number = "relative"
# cursorline = true
idle-timeout = 100
color-modes = true
mouse = true
bufferline = "always"
completion-replace = true
# lsp.display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[keys.normal]
X = "extend_line_above"
esc = ["collapse_selection", "keep_primary_selection"]
d = [":clipboard-yank-join", "delete_selection"]
y = [":clipboard-yank-join"]
p = [":clipboard-paste-after"]
P = [":clipboard-paste-before"]
R = [":clipboard-paste-replace"]

[keys.normal.space]
w = ":update"
q = ":bc"
e = ":sh explorer.exe . | exit 0"
i = ":toggle-option lsp.display-inlay-hints"
y = "no_op"
Y = "no_op"
p = "no_op"
P = "no_op"
R = "no_op"
