theme = "rose_pine"

[editor]
scrolloff = 10
line-number = "relative"
cursorline = true
color-modes = true
mouse = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"


[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
